# -*- coding: utf-8 -*-
"""Introdução a Machine learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lYfcrjfACVpmHAZ217vpNs0XlmiQBe5C
"""

# features
# possui Dente longo?
# possui Assas?
# possui Bico?
dragao1 = [0, 1, 0]
dragao2 = [0, 1, 1]
dragao3 = [1, 1, 0]

aguia1 = [0, 1, 0]
aguia2 = [1, 0, 1]
aguia3 = [1, 1, 1]

# 0 dragao // 1 aguia
treino_rede_x = [dragao1, dragao2, dragao3, aguia1, aguia2, aguia3]
treino_rede_y = [0, 0, 0, 1, 1, 1] # labels / etiqueta

from sklearn.svm import LinearSVC

redeNeural = LinearSVC()
redeNeural.fit(treino_rede_x, treino_rede_y)

animal_misterioso1 = [1, 1, 1]
animal_misterioso2 = [1, 1, 0]
animal_misterioso3 = [0, 1, 1]
teste_rede_x = [animal_misterioso1, animal_misterioso2, animal_misterioso3]
testes_rede_y = [0, 1, 1]

previsoes = redeNeural.predict(teste_rede_x)

corretos = (previsoes == testes_rede_y).sum()
total = len(teste_rede_x)
taxa_acerto = corretos/total
print("Taxa de acerto %.2f" % (taxa_acerto*100))

from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(testes_rede_y, previsoes)
print("Taxa de acerto %.2f" % (taxa_acerto*100))

