# -*- coding: utf-8 -*-
"""Introducao a Machine Learning Classificacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1njvmX9n77Ok0vgnn92axj-v3fFZv0tUF
"""

import pandas as pandas_importado

uri = "https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv"
dados_lidos_uri = pandas_importado.read_csv(uri)
dados_lidos_uri.head()

mapa_replace = {
    "home": "pagina_principal",
    "how_it_works": "como_que_roda",
    "contact": "contato",
    "bought": "comprado"
}
dados_lidos_renomeados = dados_lidos_uri.rename(columns=mapa_replace)

dados_lidos_x = dados_lidos_renomeados[["pagina_principal","como_que_roda","contato"]]
dados_lidos_x.head()
dados_lidos_y = dados_lidos_renomeados["comprado"]
dados_lidos_y.head()

dados_lidos_renomeados.shape

treino_x = dados_lidos_x[:75]
treino_y = dados_lidos_y[:75]
teste_x = dados_lidos_x[75:]
teste_y = dados_lidos_y[75:]
print("Sera utilizado %d para treino e %d para teste" % (len(treino_x), len(teste_x)))

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

modelo_rede = LinearSVC()
modelo_rede.fit(treino_x,treino_y)
previsoes_rede = modelo_rede.predict(teste_x)

pontuacao_precisao = accuracy_score(teste_y, previsoes_rede)

print("A precisao é %.2f %%" % (pontuacao_precisao*100))

"""# Utilizando biblioteca para separar treino e teste"""

from sklearn.model_selection import  train_test_split

# define a ordem dos numeros aleatorios
semente = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(dados_lidos_x, dados_lidos_y, test_size = 0.25, random_state=semente, stratify=dados_lidos_y)

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

modelo_rede = LinearSVC()
modelo_rede.fit(treino_x,treino_y)
previsoes_rede = modelo_rede.predict(teste_x)

pontuacao_precisao = accuracy_score(teste_y, previsoes_rede)

print("A precisao é %.2f %%" % (pontuacao_precisao*100))

